enum Environment { LOCAL, DEV, STAGING, PROD }

enum LoadingStatus {
  initial,
  loading,
  refresh,
  loadMore,
  complete,
  noMoreData,
  loadMoreError,
  error,
}

enum AppLanguage {
  vi,
  en,
}

enum ChangePageViewStatus {
  next,
  previous,
}

enum ScaleLevel {
  KHONG_THUONG_XUYEN,
  DUOI_150_THANG,
  DUOI_900_THANG,
  DUOI_3000_THANG,
  DUOI_6000_THANG,
  TREN_6000_THANG,
}

enum IndustryType {
  THOI_TRANG,
  MY_PHAM,
  NOI_THAT,
  ME_VA_BE,
  MAY_TINH,
  HANG_HOA_DE_VO,
  TIVI_VA_THIET_BI_GIA_DUNG,
  GIA_DUNG,
  XE_MAY_VA_PHUONG_TIEN,
  CAY_TRONG_VA_NONG_NGHIEP,
  THUC_PHAM_VA_NONG_SAN,
  DUNG_CU_VA_PHU_KIEN,
  TRANG_SUC_VA_PHU_KIEN,
  HANG_TIEU_DUNG,
  SACH_VA_VAN_PHONG_PHAM,
  KHAC,
}

enum RoleOwnerShop {
  COD_REPORT_COMING_SOON,
  REPORT_COD_IN_PROGRESS,
  CURRENT_DAY_OPERATING_ORDER_REPORT,
  EXCEL_MENU,
  VIEW_HISTORY_ON_EXCEL_MENU,
  VIEW_REMITTANCE_VERSION_DETAILS,
  VIEW_TRANSFER_VERSION_LIST,
  UPDATE_STORE,
  ADD_STAFF_TO_THE_STORE,
  ADD_USER_TO_GROUP_WITH_PERMISSIONS,
  VIEW_STORE,
  VIEW_A_LIST_OF_STORE_EMPLOYEES,
  DELETE_EMPLOYEE_FROM_STORE,
  COD_EDITING_ONLY,
  NO_NEED_TO_ENTER_OTP,
  EDIT_ORDER_ONLY_EXCLUDING_COD,
  CANCEL_ORDER,
  IN_ORDER,
  CREATE_ORDER,
  VIEW_ORDER_DETAILS,
  VIEW_FEES,
  VIEW_ORDER_LIST,
  VIEW_ORDER_HISTORY,
  EXPORT_EXCEL_FILE,
  REQUEST_FOR_MENU_REDELIVERY,
  RETURN_REQUEST,
  UPDATE_REQUEST_TICKET,
  CREATE_REQUEST_TICKET,
  VIEW_REQUEST_TICKET_DETAILS,
  VIEW_TICKET_REQUEST_LIST,
}

enum RoleEmployeeShop {
  EXCEL_MENU,
  VIEW_HISTORY_ON_EXCEL_MENU,
  EDIT_COD,
  EDIT_ORDER_DOES_NOT_INCLUDE_COD,
  CANCEL_ORDER,
  PRINT_ORDER,
  CREATE_ORDER,
  VIEW_ORDER_DETAILS,
  VIEW_FARES,
  VIEW_ORDER_LIST,
  VIEW_ORDER_HISTORY,
  EXPORT_EXCEL_FILE,
  RETURN_ORDER_REQUEST,
  RETURN_REQUEST,
}
