# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

fastlane_require 'dotenv'

before_all do
  Dotenv.overload '.env.secret.android'
  ENV["VERSION"] = Time.now.strftime "%Y.%m.%d"
  ENV["BUILD_NUMBER"] = Time.now.strftime "%H%M%S"
  ENV["CHANGELOG"] = File.read("../../CHANGELOG.md")
end

def firebase_groups(options)
  groups = options[:tester_groups] || ENV["TESTER_GROUPS"]
  UI.user_error!("Missing Firebase tester group.") if groups.to_s.strip.empty?
  groups
end

def required_release_env(name)
  value = ENV[name]
  UI.user_error!("Missing required release setting: #{name}.") if value.to_s.strip.empty?
  value
end

def required_release_file_env(name)
  path = required_release_env(name)
  UI.user_error!("Release file not found for #{name}.") unless File.file?(path)
  path
end

def push_build_tag_if_requested(options, build_tag)
  return unless options[:push_tag]

  unless git_tag_exists(tag: build_tag)
    add_git_tag(tag: build_tag)
    push_git_tags(tag: build_tag)
  end
end

default_platform(:android)

platform :android do
  desc "Build environment=dev and flavor=debug"
  lane :build_dev_debug do |options|
    build_tag = "v" + ENV["VERSION"] + "." + ENV["BUILD_NUMBER"] + "-dev-debug-Android"
    Dir.chdir("../..") do
      sh "fvm flutter clean"
      sh "./pub_get.sh"
      sh "fvm flutter build apk --release --target=lib/main_dev.dart --flavor=dev --build-name=#{ENV["VERSION"]} --build-number #{ENV["BUILD_NUMBER"]}"
    end
    firebase_app_distribution(
            app: ENV["FIREBASE_APP_ID"],
            release_notes: "#{ENV["VERSION"]} #{ENV["BUILD_NUMBER"]}\nEnvironment: Development\nFlavor: debug\nChange: #{ENV["CHANGELOG"]}",
            apk_path: "../build/app/outputs/apk/dev/release/app-dev-release.apk",
            firebase_cli_token: ENV["FIREBASE_TOKEN"],
            groups: firebase_groups(options)
        )
    # slack(
    #   slack_url: ENV["SLACK_URL"],
    #   message: "A new `Android` app version is available on `Firebase`. :fire:  <https://appdistribution.firebase.google.com/testerapps/#{ENV["FIREBASE_APP_ID"]}|Download here>  :fire:\nVersion: `#{ENV["VERSION"]} #{ENV["BUILD_NUMBER"]}`\nEnvironment: `Development`"
    # )
    push_build_tag_if_requested(options, build_tag)
  end

  desc "Build environment=staging and flavor=staging"
  lane :build_staging_staging do |options|
    build_tag = "v" + ENV["VERSION"] + "." + ENV["BUILD_NUMBER"] + "-staging-staging-Android"
    Dir.chdir("../..") do
      sh "fvm flutter clean"
      sh "./pub_get.sh"
      sh "fvm flutter build apk --release --target=lib/main_staging.dart --flavor=staging --build-name=#{ENV["VERSION"]} --build-number #{ENV["BUILD_NUMBER"]}"
    end
    firebase_app_distribution(
            app: ENV["FIREBASE_APP_ID"],
            release_notes: "#{ENV["VERSION"]} #{ENV["BUILD_NUMBER"]}\nEnvironment: Staging\nFlavor: staging\nChange: #{ENV["CHANGELOG"]}",
            apk_path: "../build/app/outputs/apk/staging/release/app-staging-release.apk",
            firebase_cli_token: ENV["FIREBASE_TOKEN"],
            groups: firebase_groups(options)
        )
    # slack(
    #   slack_url: ENV["SLACK_URL"],
    #   message: "A new `Android` app version is available on `Firebase`. :fire:  <https://appdistribution.firebase.google.com/testerapps/#{ENV["FIREBASE_APP_ID"]}|Download here>  :fire:\nVersion: `#{ENV["VERSION"]} #{ENV["BUILD_NUMBER"]}`\nEnvironment: `Development`"
    # )
    push_build_tag_if_requested(options, build_tag)
  end
    
  desc "Build environment=prod and flavor=release"
  lane :build_prod_release do |options|
    build_tag = "v" + ENV["VERSION"] + "." + ENV["BUILD_NUMBER"] + "-prod-release-Android"
    Dir.chdir("../..") do
      sh "fvm flutter clean"
      sh "./pub_get.sh"
      sh "fvm flutter build apk --release --target=lib/main_prod.dart --flavor=prod --build-name=#{ENV["VERSION"]} --build-number #{ENV["BUILD_NUMBER"]}"
    end
    firebase_app_distribution(
            app: ENV["FIREBASE_APP_ID"],
            release_notes: "#{ENV["VERSION"]} #{ENV["BUILD_NUMBER"]}\nEnvironment: Production\nFlavor: release\nChange: #{ENV["CHANGELOG"]}",
            apk_path: "../build/app/outputs/apk/prod/release/app-prod-release.apk",
            firebase_cli_token: ENV["FIREBASE_TOKEN"],
            groups: firebase_groups(options)
        )
    # slack(
    #   slack_url: ENV["SLACK_URL"],
    #   message: "A new `Android` app version is available on `Firebase`. :fire:  <https://appdistribution.firebase.google.com/testerapps/#{ENV["FIREBASE_APP_ID"]}|Download here>  :fire:\nVersion: `#{ENV["VERSION"]} #{ENV["BUILD_NUMBER"]}`\nEnvironment: `Production`"
    # )
    push_build_tag_if_requested(options, build_tag)
  end

  desc "Build and upload store Android"
  lane :build_store do |options|
    package_name = required_release_env("ANDROID_PACKAGE_NAME")
    json_key_path = required_release_file_env("GOOGLE_PLAY_JSON_KEY_PATH")
    version_name = flutter_version()["version_name"]
    version_code = flutter_version()["version_code"]
    build_tag = "Release-" + version_name + "(" + version_code + ")"
    Dir.chdir("../..") do
      sh "fvm flutter clean"
      sh "./pub_get.sh"
      sh "fvm flutter build appbundle --target=lib/main_prod.dart --flavor=prod"
    end
    upload_to_play_store(
      package_name: package_name,
      json_key: json_key_path,
      skip_upload_apk: true,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_changelogs: true,
      version_name: version_name,
      version_code: version_code,
      release_status: 'draft',
      track: 'production',
      aab: "../build/app/outputs/bundle/prodRelease/app-prod-release.aab"
    )
    # slack(
    #   slack_url: ENV["SLACK_URL"],
    #   message: "A new `Android` app version is available on `Google Play`. :fire:  Version: `#{version_code}`"
    # )
    push_build_tag_if_requested(options, build_tag)
  end
end
